### ISSUE TITLE
 Could not find any downloads that satisfy the requirement Flask-Pushjack

### ISSUE THREAD

**Issue by jianglin612** [dgilland/flask-pushjack#1]
Getting the following error when trying to PIP install. Any solutions?

**Comment by dgilland** [comment]
I just uploaded the first release to PyPi. I verified it's now installable via pip.

**Comment by jianglin612** [comment]
awesome! thanks! how stable/up to date is all  this code?

**Comment by dgilland** [comment]
This Flask extension is fairly stable even though there's only been 1 release. It's mainly a thin wrapper around the [pushjack](https://github.com/dgilland/pushjack) library which just hooks up to its `APNSClient` and `GCMClient` classes and exposes the `send`, `send_bulk`, and `get_expired_tokens` methods.

As for pushjack, I don't have any immediate plans to break backwards compatibility with the `send` and `send_bulk` functions before getting to a `v1` release. I'm mostly focusing on improving the internals.

The lastest update for pushjack was 2015-03-28 so it's fairly recent. There are a few [outstanding issues](https://github.com/dgilland/pushjack/issues) mostly related to error handling which I plan to tackle for `v1`.

**Comment by jianglin612** [comment]
Could you provide some more info on how to use? I tried setting it up as suggested but am getting the following message back everytime: 

{
    "message": "", 
    "status": null
}

I know the PEM file works because I have gotten it to work via PHP before.

**Comment by dgilland** [comment]
Can you show me the code you are using?

**Comment by dgilland** [comment]
Just a small example that demonstrates your issue.
