### ISSUE TITLE
How do I use **options?

### ISSUE THREAD

**Issue by jeongmincha** [dgilland/flask-pushjack#3]
In flask-pushjack, the below code is for sending push notifications.
```
res = client.send(token, alert, **options)
```
But, I don't know what to put in **options. How do I use **options?

**Comment by dgilland** [comment]
Documentation for that can be found at:

- https://github.com/dgilland/pushjack
- http://pushjack.readthedocs.io/en/latest/

**Comment by jeongmincha** [comment]
Thank you for you answer.
